# globals.R declares global variable names used in NSE
# (non-standard evaluation) expressions within the package.

#' Global Variables Used by FIA Query Functions
#'
#' Declares column names used in non-standard evaluation by dplyr
#' operations within the package. These declarations suppress
#' false-positive NOTES generated by R CMD check.
#'
#' @name FIADB.diRect-globals
#' @keywords internal
NULL

utils::globalVariables(
  c(
    "SE_OF_ESTIMATE_PCT",
    "SE_OF_ESTIMATE",
    "VAR_OF_ESTIMATE",
    "TOTAL_PLOTS",
    "NON_ZERO_PLOTS",
    "TOT_POP_AC"
  )
)

